export const DASHBOARD_ROUTES = {
  dashboard: "/admin/dashboard",
  addInvoice: "/add-invoice",
  customers: "/admin/customers",
  suppliers: "/admin/supplier",
  purchases: "/admin/purchase",
  expenses: "/admin/expenses",
  invoices: "/admin/invoices",
  inventory: "/admin/inventory",
  services: "/admin/services",
  makes: "/admin/makes",
  balance: "/admin/balance",
  users: "/admin/users",
  paymentMethods: "/admin/payment-methods",
  settings: "/admin/settings",
  dbBackup: "/admin/db-backup",
  transactions: "/admin/transactions",
  loanTransactions: "/admin/loan-transactions",
  billing: "/admin/ams/billing",
};
